import { Inter } from "next/font/google";
import "@/app/globals.css";
import { Toaster } from "sonner";
import SessionWrapper from "@/components/SessionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Login Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionWrapper>
        <body className={inter.className}>
          {children}
          <Toaster richColors />
        </body>
      </SessionWrapper>
    </html>
  );
}
