import { Inter } from "next/font/google";
import "@/app/globals.css";

import SessionWrapper from "@/components/SessionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "X clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionWrapper>
        <body className={inter.className}>
          <div className="container mx-auto flex min-h-screen w-full justify-between">
            {children}
          </div>
        </body>
      </SessionWrapper>
    </html>
  );
}
